# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 11) do

  create_table "categories", :force => true do |t|
    t.column "parent_id", :integer
    t.column "name",      :string
  end

  create_table "deals", :force => true do |t|
    t.column "status", :integer
  end

  create_table "offers", :force => true do |t|
    t.column "name",              :string
    t.column "short_description", :string
    t.column "long_description",  :string
    t.column "picture_url",       :string
    t.column "user_id",           :integer
    t.column "category_id",       :integer
  end

  add_index "offers", ["user_id"], :name => "fk_offers_users"
  add_index "offers", ["category_id"], :name => "fk_offers_category"

  create_table "requests", :force => true do |t|
    t.column "offer_id",    :integer
    t.column "category_id", :integer
  end

  add_index "requests", ["offer_id"], :name => "fk_requests_offers"
  add_index "requests", ["category_id"], :name => "fk_requests_categories"

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "index_sessions_on_session_id"
  add_index "sessions", ["updated_at"], :name => "index_sessions_on_updated_at"

  create_table "trans_cats", :force => true do |t|
    t.column "cat_id",      :integer
    t.column "ancestor_id", :integer
  end

  create_table "transfers", :force => true do |t|
    t.column "deal_id",      :integer
    t.column "from_user_id", :integer
    t.column "to_user_id",   :integer
    t.column "offer_id",     :integer
    t.column "status",       :integer
  end

  add_index "transfers", ["from_user_id"], :name => "fk_transfers_from_users"
  add_index "transfers", ["to_user_id"], :name => "fk_transfers_to_users"
  add_index "transfers", ["offer_id"], :name => "fk_transfers_offers"
  add_index "transfers", ["deal_id"], :name => "fk_transfers_deals"

  create_table "users", :force => true do |t|
    t.column "login",           :string
    t.column "hashed_password", :string
    t.column "salt",            :string
    t.column "firstname",       :string
    t.column "lastname",        :string
    t.column "street",          :string
    t.column "zipcode",         :string
    t.column "city",            :string
    t.column "country",         :string
  end

end
